name: Build image

on:
  push:
    branches: ["**"]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      TAG: ${{ github.head_ref || github.ref_name }}
      TYPES: |
        qcow2
        vmdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push bootc container image
        run: |
          docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}" .
          docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"

      - name: Build VM images from bootc image
        id: bib
        uses: osbuild/bootc-image-builder-action@v0.0.2
        with:
          image: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          config-file: ./bootc/config.toml
          types: ${{ env.TYPES }}

      - name: Generate OVA file
        run: |
          sudo apt-get update && sudo apt-get install -y python3
          sudo mkdir -p ${{ steps.bib.outputs.output-directory }}/ova
          
          ls -l ${{ steps.bib.outputs.output-directory }}

          VMDK_FILE="${{ steps.bib.outputs.output-directory }}/vmdk/disk.vmdk"
          echo $VMDK_FILE
          sudo python3 ovfbuilder.py \
            --disk "$VMDK_FILE" \
            --template ovf_template.xml \
            --out "${{ steps.bib.outputs.output-directory }}/ova/disk.ova"

      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bootc-${{ env.TAG }}
          path: ${{ steps.bib.outputs.output-directory }}
          if-no-files-found: error

      - name: Add release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ${{ steps.bib.outputs.output-directory }}/qcow2/*.qcow2
            ${{ steps.bib.outputs.output-directory }}/vmdk/*.vmdk
            ${{ steps.bib.outputs.output-directory }}/ova/*.ova
